# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_profile_download_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
