# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField(default=0)),
                ('resume_status', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('work_ex', models.FloatField(default=0.0)),
                ('analytic_ex', models.FloatField(default=0.0)),
                ('current_location', models.CharField(blank=True, max_length=30)),
                ('nearest_city', models.CharField(blank=True, max_length=30)),
                ('preferred_location', models.CharField(blank=True, max_length=30)),
                ('ctc', models.FloatField(default=0.0)),
                ('current_employer', models.CharField(blank=True, max_length=100)),
                ('current_designation', models.CharField(blank=True, max_length=100)),
                ('year_of_passing', models.IntegerField(blank=True, null=True)),
                ('skills', models.ManyToManyField(to='core.Skills')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='ug_course',
            field=models.ManyToManyField(to='core.Course'),
        ),
    ]
