# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180813_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='core.Location'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='nearest_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearest_city', to='core.Location'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='preferred_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_location', to='core.Location'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='core.Skills'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='ug_course',
            field=models.ManyToManyField(blank=True, null=True, to='core.Course'),
        ),
    ]
